from __future__ import annotations

from datetime import date

from sqlalchemy import text

from app.db.models import Base
from app.db.session import engine


DEFAULT_PROGRAM_LESSONS = [
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b1",
        "block_title": "Кикоф программы и блока",
        "block_order": 1,
        "lesson_key": "s1_b1_kickoff",
        "lesson_number": None,
        "lesson_title": "Кикоф программы и блока",
        "date_start": date(2026, 5, 21),
        "date_end": None,
        "date_text": "21.05.2026",
        "speaker": None,
        "content_status": "запись встречи, презентация, ссылка на анкету",
        "material_format": "запись встречи, презентация, ссылка на анкету",
        "hr_moderator_role": None,
        "sort_order": 10,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b2",
        "block_title": "Бизнес-консалтинг",
        "block_order": 2,
        "lesson_key": "s1_b2_l1",
        "lesson_number": 1,
        "lesson_title": "Занятие 1. Логика консалтингового бизнеса и Time to Cash",
        "date_start": date(2026, 5, 26),
        "date_end": None,
        "date_text": "26.05.2026",
        "speaker": "Рахманов А.",
        "content_status": "уточнить",
        "material_format": "презентация",
        "hr_moderator_role": None,
        "sort_order": 20,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b2",
        "block_title": "Бизнес-консалтинг",
        "block_order": 2,
        "lesson_key": "s1_b2_l2",
        "lesson_number": 2,
        "lesson_title": "Занятие 2. Организационные модели консалтингового бизнеса",
        "date_start": date(2026, 6, 2),
        "date_end": None,
        "date_text": "02.06.2026",
        "speaker": "Берштейн Т. Рахманов А.",
        "content_status": "уточнить",
        "material_format": "презентация + доп.материалы",
        "hr_moderator_role": None,
        "sort_order": 30,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b2",
        "block_title": "Бизнес-консалтинг",
        "block_order": 2,
        "lesson_key": "s1_b2_l3",
        "lesson_number": 3,
        "lesson_title": "Занятие 3. Практикум",
        "date_start": date(2026, 6, 9),
        "date_end": None,
        "date_text": "09.06.2026",
        "speaker": "Рахманов А.",
        "content_status": "уточнить",
        "material_format": "кейс",
        "hr_moderator_role": "фасилитация групповой работы",
        "sort_order": 40,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b2",
        "block_title": "Бизнес-консалтинг",
        "block_order": 2,
        "lesson_key": "s1_b2_l4",
        "lesson_number": 4,
        "lesson_title": "Занятие 4. Итоговая сборка блока",
        "date_start": date(2026, 6, 16),
        "date_end": None,
        "date_text": "16.06.2026",
        "speaker": "Рахманов А.",
        "content_status": "уточнить",
        "material_format": "синтез по домашкам + вопросы от участников",
        "hr_moderator_role": "фидбек по применению в департаментах + проработка инструментов в рекомендуемые практики (?)",
        "sort_order": 50,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b3",
        "block_title": "Стратегия",
        "block_order": 3,
        "lesson_key": "s1_b3_l1",
        "lesson_number": 1,
        "lesson_title": "Занятие 1. Стратегия как инструмент лидера",
        "date_start": date(2026, 6, 23),
        "date_end": None,
        "date_text": "23.06.2026",
        "speaker": "Семенов А.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 60,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b3",
        "block_title": "Стратегия",
        "block_order": 3,
        "lesson_key": "s1_b3_l2",
        "lesson_number": 2,
        "lesson_title": "Занятие 2. Фокус и стратегический выбор",
        "date_start": date(2026, 6, 30),
        "date_end": None,
        "date_text": "30.06.2026",
        "speaker": "Семенов А.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 70,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b3",
        "block_title": "Стратегия",
        "block_order": 3,
        "lesson_key": "s1_b3_l3",
        "lesson_number": 3,
        "lesson_title": "Занятие 3. Ресурсы, изменения и сценарное планирование",
        "date_start": date(2026, 7, 7),
        "date_end": None,
        "date_text": "07.07.2026",
        "speaker": "Павлов Я. Семенов А.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 80,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b3",
        "block_title": "Стратегия",
        "block_order": 3,
        "lesson_key": "s1_b3_l4",
        "lesson_number": 4,
        "lesson_title": "Занятие 4. Реализация стратегии в сопротивляющейся системе",
        "date_start": date(2026, 7, 14),
        "date_end": None,
        "date_text": "14.07.2026",
        "speaker": "Семенов А. Сытин Д.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 90,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b4",
        "block_title": "Экономика и финансы",
        "block_order": 4,
        "lesson_key": "s1_b4_l1",
        "lesson_number": 1,
        "lesson_title": "Занятие 1. Экономика проектов и маржа",
        "date_start": date(2026, 7, 21),
        "date_end": None,
        "date_text": "21.07.2026",
        "speaker": "Сафронов С.",
        "content_status": "уточнить",
        "material_format": "презентация + практика",
        "hr_moderator_role": None,
        "sort_order": 100,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b4",
        "block_title": "Экономика и финансы",
        "block_order": 4,
        "lesson_key": "s1_b4_l2",
        "lesson_number": 2,
        "lesson_title": "Занятие 2. Финансовая модель КОРУС",
        "date_start": date(2026, 7, 28),
        "date_end": None,
        "date_text": "28.07.2026",
        "speaker": "Макарова Ю.",
        "content_status": "уточнить",
        "material_format": "презентация + практика",
        "hr_moderator_role": None,
        "sort_order": 110,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b4",
        "block_title": "Экономика и финансы",
        "block_order": 4,
        "lesson_key": "s1_b4_l3",
        "lesson_number": 3,
        "lesson_title": "Занятие 3. Финансовое мышление руководителя",
        "date_start": date(2026, 8, 4),
        "date_end": None,
        "date_text": "04.08.2026",
        "speaker": "Карлик М.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 120,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b4",
        "block_title": "Экономика и финансы",
        "block_order": 4,
        "lesson_key": "s1_b4_l4",
        "lesson_number": 4,
        "lesson_title": "Занятие 4. Интеграция и разбор",
        "date_start": date(2026, 8, 11),
        "date_end": None,
        "date_text": "11.08.2026",
        "speaker": "Макарова Ю. Сафронов С.",
        "content_status": "уточнить",
        "material_format": None,
        "hr_moderator_role": None,
        "sort_order": 130,
        "is_active": True,
    },
    {
        "season_key": "s1",
        "season_title": "Бизнес",
        "block_key": "s1_b5",
        "block_title": "Подведение итогов сезона",
        "block_order": 5,
        "lesson_key": "s1_b5_final",
        "lesson_number": None,
        "lesson_title": "Очная сессия в СПб",
        "date_start": date(2026, 8, 17),
        "date_end": date(2026, 8, 23),
        "date_text": "17.08 - 23.08",
        "speaker": None,
        "content_status": None,
        "material_format": "бизнес-игра, страт-сессия, командообразующий опыт",
        "hr_moderator_role": None,
        "sort_order": 140,
        "is_active": True,
    },
]


async def init_db() -> None:
    async with engine.begin() as conn:
        await conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        await conn.run_sync(Base.metadata.create_all)
        await conn.execute(text("ALTER TABLE message_feedback ADD COLUMN IF NOT EXISTS reason varchar(50)"))
        await conn.execute(text("ALTER TABLE documents ADD COLUMN IF NOT EXISTS lesson_key varchar(100)"))
        await conn.execute(text("ALTER TABLE documents ADD COLUMN IF NOT EXISTS lesson_date date"))
        await conn.execute(text("ALTER TABLE documents ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE program_media ADD COLUMN IF NOT EXISTS lesson_key varchar(100)"))
        await conn.execute(text("ALTER TABLE program_media ADD COLUMN IF NOT EXISTS lesson_date date"))
        await conn.execute(text("ALTER TABLE program_media ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE homeworks ALTER COLUMN status SET DEFAULT 'active'"))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_documents_lesson_key ON documents(lesson_key)"))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_documents_lesson_date ON documents(lesson_date)"))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_program_media_lesson_key ON program_media(lesson_key)"))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_program_media_lesson_date ON program_media(lesson_date)"))
        await conn.execute(
            text(
                """
                INSERT INTO program_lessons (
                    season_key,
                    season_title,
                    block_key,
                    block_title,
                    block_order,
                    lesson_key,
                    lesson_number,
                    lesson_title,
                    date_start,
                    date_end,
                    date_text,
                    speaker,
                    content_status,
                    material_format,
                    hr_moderator_role,
                    sort_order,
                    is_active
                )
                VALUES (
                    :season_key,
                    :season_title,
                    :block_key,
                    :block_title,
                    :block_order,
                    :lesson_key,
                    :lesson_number,
                    :lesson_title,
                    :date_start,
                    :date_end,
                    :date_text,
                    :speaker,
                    :content_status,
                    :material_format,
                    :hr_moderator_role,
                    :sort_order,
                    :is_active
                )
                ON CONFLICT (lesson_key) DO UPDATE SET
                    season_title = EXCLUDED.season_title,
                    block_key = EXCLUDED.block_key,
                    block_title = EXCLUDED.block_title,
                    block_order = EXCLUDED.block_order,
                    lesson_number = EXCLUDED.lesson_number,
                    lesson_title = EXCLUDED.lesson_title,
                    date_start = EXCLUDED.date_start,
                    date_end = EXCLUDED.date_end,
                    date_text = EXCLUDED.date_text,
                    speaker = EXCLUDED.speaker,
                    content_status = EXCLUDED.content_status,
                    material_format = EXCLUDED.material_format,
                    hr_moderator_role = EXCLUDED.hr_moderator_role,
                    sort_order = EXCLUDED.sort_order,
                    is_active = EXCLUDED.is_active
                """
            ),
            DEFAULT_PROGRAM_LESSONS,
        )
